name: Deploy Node.js Backend and React Frontend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Set up SSH
        run: |
          # Create .ssh directory with secure permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Properly format the private key
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        
          # Add EC2 host to known_hosts
          ssh-keyscan -t rsa ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts || {
            echo "Error adding host to known_hosts"
            exit 1
          }
          chmod 644 ~/.ssh/known_hosts
        
          # Verify setup
          echo "SSH setup complete. Known hosts:"
          cat ~/.ssh/known_hosts

      - name: Build React Frontend
        run: |
          npm ci
          npm run build

      - name: Deploy React Frontend
        env:
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          EC2_USER: ${{ secrets.AWS_EC2_USER }}
          FRONTEND_DIR: ${{ secrets.FRONTEND_DIR }}
        run: |
          # First verify connection
          echo "Testing connection to $EC2_USER@$EC2_HOST..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "echo 'SSH successful!'"
          
          # Deploy in two stages
          echo "Copying files to temp location..."
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" build/ $EC2_USER@$EC2_HOST:~/temp-build/
          
          echo "Moving files to final location..."
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "
            sudo mkdir -p $FRONTEND_DIR && \
            sudo chown -R $EC2_USER:$EC2_USER $FRONTEND_DIR && \
            sudo chmod -R 755 $FRONTEND_DIR && \
            sudo rsync -a --delete ~/temp-build/ $FRONTEND_DIR/ && \
            echo 'Deployment completed successfully'
          "

      - name: Deploy Node.js Backend
        env:
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          EC2_USER: ${{ secrets.AWS_EC2_USER }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" build/ $EC2_USER@$EC2_HOST:$APP_DIR \
            --exclude='node_modules' \
            --exclude='.env'

      - name: Restart Node.js Service
        env:
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          EC2_USER: ${{ secrets.AWS_EC2_USER }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
          set -e
          echo "Deploying Node.js Application..."
          cd $APP_DIR
          
          if ! command -v pm2 &> /dev/null; then
            echo "Installing PM2..."
            sudo npm install -g pm2
          fi
          
          echo "Installing dependencies..."
          npm ci --only=production
          pm2 restart all || pm2 start app.js --name "my-app"
          EOF
