name: Deploy React Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          ls -la build/ # Verify build files

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          EC2_USER: ${{ secrets.AWS_EC2_USER }}
          DEPLOY_DIR: ${{ secrets.FRONTEND_DEPLOY_DIR }} # e.g. /var/www/html
        run: |
          # Create directory and set permissions
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "
            sudo mkdir -p $DEPLOY_DIR && \
            sudo chown -R $EC2_USER:$EC2_USER $DEPLOY_DIR && \
            sudo chmod -R 755 $DEPLOY_DIR
          "
          
          # Deploy files
          rsync -avz --delete \
            --no-perms --no-group \
            --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r \
            -e "ssh -i ~/.ssh/id_rsa" \
            build/ $EC2_USER@$EC2_HOST:$DEPLOY_DIR/

          # Verify deployment
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "ls -la $DEPLOY_DIR"
