name: Deploy Node.js Backend and React Frontend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Set up SSH
        run: |
          # Create .ssh directory with secure permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Properly format the private key (handles newlines in GitHub secrets)
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        
          # Add EC2 host to known_hosts with all key types
          ssh-keyscan -t rsa  "${{ secrets.AWS_EC2_HOST }}" >> ~/.ssh/known_hosts || {
            echo "Error adding host to known_hosts"
            exit 1
          }
          chmod 644 ~/.ssh/known_hosts
        
          # Verify setup
          echo "SSH setup complete. Known hosts:"
          cat ~/.ssh/known_hosts

      # Install dependencies and build React
      - name: Build React Frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..

      # Copy built React files to EC2
      - name: Deploy React Frontend
        env:
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          EC2_USER: ${{ secrets.AWS_EC2_USER }}
          FRONTEND_DIR: ${{ secrets.FRONTEND_DIR }}
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" frontend/build/ ${AWS_EC2_USER}@${AWS_EC2_HOST}:${FRONTEND_DIR}

      # Install Node.js backend dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci
          cd ..

      # Copy backend files to EC2
      - name: Deploy Node.js Backend
        env:
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          EC2_USER: "ubuntu"
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" backend/ ${AWS_EC2_USER}@${AWS_EC2_HOST}:${APP_DIR} \
          --exclude='node_modules' \
          --exclude='.env'

      # Connect to EC2 and restart Node.js service
      - name: Restart Node.js Service
        env:
          EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          EC2_USER: ${{ secrets.AWS_EC2_USER }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          ssh ${AWS_EC2_USER}@${AWS_EC2_HOST} << 'EOF'
          set -e
          echo "Deploying Node.js Application..."
          cd ${APP_DIR}
          
          # Install PM2 if not present
          if ! command -v pm2 &> /dev/null; then
            echo "Installing PM2..."
            sudo npm install -g pm2
          fi
          
          # Install production dependencies
          echo "Installing dependencies..."
          npm ci --only=production
          pm2 restart all || pm2 start app.js --name "my-app"
          EOF
